# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_char.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1443, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 541, 511))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 70, 541, 511))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 620, 200, 50))
        self.pushButton.setObjectName("pushButton")
        self.filebutton = QtWidgets.QPushButton(self.centralwidget)
        self.filebutton.setGeometry(QtCore.QRect(1130, 620, 200, 50))
        self.filebutton.setObjectName("filebutton")
        self.clearbutton = QtWidgets.QPushButton(self.centralwidget)
        self.clearbutton.setGeometry(QtCore.QRect(630, 620, 200, 50))
        self.clearbutton.setObjectName("clearbutton")
        self.result_msg = QtWidgets.QLabel(self.centralwidget)
        self.result_msg.setGeometry(QtCore.QRect(1350, 450, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.result_msg.setFont(font)
        self.result_msg.setText("")
        self.result_msg.setObjectName("result_msg")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(810, 20, 91, 31))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(1180, 30, 87, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "摄像头1"))
        self.label_2.setText(_translate("MainWindow", "摄像头2"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        self.filebutton.setText(_translate("MainWindow", "存储目录设置"))
        self.clearbutton.setText(_translate("MainWindow", "暂停/恢复"))
        self.label_3.setText(_translate("MainWindow", "摄像头1"))
        self.label_4.setText(_translate("MainWindow", "摄像头2"))
